arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - bases
    #- B_rot->In_1
    #- In_1->Join
    #- Join->In_2
    #- In_2->EE
    #- Join->Out_1
    #- Join->Out_2
    #- GripperMount->GripperAxis
    #- GripperFingerA1->GripperFingerA2
    #- GripperFingerA2->GripperFingerA3
    #- GripperFingerA3->GripperFingerA4
    #- GripperFingerA4->GripperFingerA5
    #- GripperFingerB1->GripperFingerB2
    #- GripperFingerB2->GripperFingerB3
    #- GripperFingerB3->GripperFingerB4
    #- GripperFingerB4->GripperFingerB5
    #- GripperFingerC1->GripperFingerC2
    #- GripperFingerC2->GripperFingerC3
    #- GripperFingerC3->GripperFingerC4
    #- GripperFingerC4->GripperFingerC5